//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int IDPicture { get; set; }
        public string Name { get; set; }
        public string YearOfPublication { get; set; }
        public string ArtistName { get; set; }
        public string DateOfBirth { get; set; }
    }
}
